### ISSUE TITLE
ping: new tag for 0.4.1 release

### ISSUE THREAD

**Issue by tfuxu** [GradienceTeam/Packages#11]
There is a mistake made by me in 0.4.1 release, some paths weren't updated before making `0.4.1` tag, such as project version in the main `meson.build` file, causing Gradience to report this version incorrectly as 0.4.0. 

Package maintainers are requested to update their packages to `0.4.1-patch1` tag or commit `af81166e2bca21b35948356753ea08ce5ba44ed0`.

CC @0xMRTT @LyesSaadi

**Comment by LyesSaadi** [comment]
https://github.com/flathub/com.github.GradienceTeam.Gradience/pull/10

**Comment by LyesSaadi** [comment]
https://copr.fedorainfracloud.org/coprs/lyessaadi/gradience/build/5615803/
