### ISSUE TITLE
bug: python(abi) = 3.11 missing on Fedora copr

### ISSUE THREAD

**Issue by minosimo** [GradienceTeam/Packages#13]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello, when trying to install on Fedora 39 I get a dependency error:
`nothing provides python(abi) = 3.11 needed by gradience-0.4.1-2.fc39.noarch from copr:copr.fedorainfracloud.org:lyessaadi:gradience`
Python is version 3.12. I also installed python3.11, and had no luck searching for solutions.

### OS

Fedora Linux 39

### Installation method

Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by LyesSaadi** [comment]
Yup, working on it. A dependency wants Pillow 9 and F39 has Pillow 10, preventing the immediate switch. I need to test if it works.

**Comment by LyesSaadi** [comment]
https://copr.fedorainfracloud.org/coprs/lyessaadi/gradience/build/6610078/

**Comment by minosimo** [comment]
Thank you! Really appreciate you maintaining a copr.

**Comment by LyesSaadi** [comment]
You're welcome :) !
