### ISSUE TITLE
feat: upgrade to 0.2.2

### ISSUE THREAD

**Issue by 0xMRTT** [GradienceTeam/Packages#7]
### Feature description

Released few minutes ago

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

**Comment by 0xMRTT** [comment]
?

**Comment by 0xMRTT** [comment]
Oh, got an idea, we can publish an issue when a new release and GitHub actions will automatically update everything for the next version

**Comment by LyesSaadi** [comment]
Built in copr and flathub ?

**Comment by LyesSaadi** [comment]
> Oh, got an idea, we can publish an issue when a new release and GitHub actions will automatically update everything for the next version

GitHub Actions are not the answer to everything xD ! Plus, they can break everything if a new dependency is needed, for example.

**Comment by 0xMRTT** [comment]
Is 0.2.2 on Flathub ?

**Comment by LyesSaadi** [comment]
Yup

**Comment by 0xMRTT** [comment]
Great 🎉
